---
- name: Install editors
  pacman:
    name: "{{ editors }}"
    state: present

- name: Neovim 
  tags:
    - vimrc 
    - nvimrc 
    - neovimrc 
    - rc 
  block: 
    - name: Neovim | Push config
      copy:
        src: rc/nvim
        dest: /home/{{ user.name }}/.config
        mode: preserve 
        owner: "{{ user.name }}"
        group: "{{ user.group }}"   

    - name: Neovim | Install vim-plug-git
      aur:
        name: vim-plug-git
        user: "{{ user.name }}"

    - name: Neovim | Install python support
      pip:
        name: neovim
        state: latest

    - name: Neovim | Install npm
      pacman:
        name: npm
        state: present

    - name: Neovim | Install plugins
      become: yes
      become_user: "{{ user.name }}"
      shell: nvim +PlugInstall +qall --headless
      
