- hosts: localhost
  connection: local
  vars_files:
    - localhost_vars.yml
  roles:
    - kewlfft.aur
    - { role: secrets, tags: ['secrets'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: shell, tags: ['shell'] }
    - { role: neovim, tags: ['neovim'] }
    - { role: tmux, tags: ['tmux'] }
    - { role: gnome, tags: ['gnome'] }
    - { role: shell, tags: ['shell'] }
