- hosts: localhost
  connection: local
  vars_files:
    - localhost_vars.yml
  roles:
    - kewlfft.aur
    - { role: base, tags: ['base'] }
    - { role: bitwarden, tags: ['bitwarden'] }
    - { role: bspwm, tags: ['bspwm'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: gnome, tags: ['gnome'] }
    - { role: kitty, tags: ['kitty'] }
    - { role: neovim, tags: ['neovim'] }
    - { role: qutebrowser, tags: ['qutebrowser'] }
    - { role: taskwarrior, tags: ['taskwarrior'] }
    - { role: surface, tags: ['surface'] }
    - { role: secrets, tags: ['secrets'] }
    - { role: shell, tags: ['shell'] }
    - { role: tmux, tags: ['tmux'] }
    - { role: vpn, tags: ['vpn'] }
    - { role: x, tags: ['x'] }
