---
- hosts: all
  become: yes
  roles:
    - { role: secrets, tags: ['secrets'] }
    - { role: base, tags: ['base'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: editors, tags: ['editors'] }
    - { role: cron, tags: ['cron'] }
    - { role: x, tags: ['x'] }

    - { role: lf, tags: ['lf'] }
    - { role: kitty, tags: ['kitty'] }
    - { role: taskwarrior, tags: ['taskwarrior'] }
    - { role: qutebrowser, tags: ['qutebrowser'] }
    - { role: bitwarden, tags: ['bitwarden'] }

    - { role: desktop, tags: ['desktop'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: playback, tags: ['playback'] }
    - { role: redshift, tags: ['redshift'] }
    - { role: sound, tags: ['sound'] }
    - { role: ripgrep, tags: ['ripgrep'] }
    - { role: blacklist, tags: ['blacklist'] }
