---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: blacklist, tags: ['blacklist'] }
    - { role: editors, tags: ['editors'] }
    - { role: cron, tags: ['cron'] }
    - { role: x, tags: ['x'] }
    - { role: desktop, tags: ['desktop'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: playback, tags: ['playback'] }
    - { role: taskwarrior, tags: ['taskwarrior'] }
    - { role: redshift, tags: ['redshift'] }
    - { role: sound, tags: ['sound'] }
    - { role: ripgrep, tags: ['ripgrep'] }