---
- name: Install scripts
  tags:
    - bin
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item | basename | splitext | first }}"
    mode: 0755 
  with_fileglob:
    - files/bin/*

- name: Install packages
  block:
    - name: yay
      aur:
        name: 
          - bspwm-git
          - polybar-git
        user: "{{ user.name }}"

- name: Mimeapps
  block:
    - name: Verify that default applications file exists
      file:
        path: /etc/xdg/mimeapps.list
        state: touch
        access_time: preserve
        modification_time: preserve

    - name: Verify header in default applications file
      lineinfile:
        dest: /etc/xdg/mimeapps.list
        state: present
        line: '[Default Applications]'
        insertbefore: BOF

- name: bspwm
  tags:
    - bspwm
    - bspwmrc
    - config
  vars:
    BSPWM_SOCKET: /tmp/bspwm-socket
  block: 
    - name: Push bspwm config
      copy:
        mode: preserve 
        src: rc/bspwm
        dest: /home/{{ user.name }}/.config
        owner: "{{ user.name }}"
        group: "{{ user.group }}"

    - name: Monitors
      blockinfile:
        path: /home/{{ user.name }}/.config/bspwm/bspwmrc
        marker: "# {mark} Monitors"
        block: |
          MONITOR={{ item.name }} polybar --reload example &
      loop: "{{ bspwm.monitors }}"

    - name: Desktops
      blockinfile:
        path: /home/{{ user.name }}/.config/bspwm/bspwmrc
        marker: "# {mark} Desktops"
        block: |
          bspc monitor {{ item.name }} -d {{ item.desktops | join(' ')}}
      loop: "{{ bspwm.monitors }}"

    - name: set BSPWM_SOCKET
      lineinfile:
        dest: /home/{{ user.name }}/.profile
        regexp: '^\s*export BSPWM_SOCKET='
        line: 'export BSPWM_SOCKET="{{ BSPWM_SOCKET }}"'

    - name: Reload bspwm
      command: bspc wm -r
      environment:
        BSPWM_SOCKET: "{{ BSPWM_SOCKET }}"
  
- name: polybar
  tags:
    - polybar
    - polybarrc
    - config
  block: 
    - name: Create polybar directory
      file:
        path: /home/{{ user.name }}/.config/polybar
        state: directory
        owner: "{{ user.name }}"
        group: "{{ user.group }}"

    - name: Push polybar config
      copy: 
        src: rc/polybarrc
        dest: /home/{{ user.name }}/.config/polybar/config
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
