---
- name: Install bspwm-git
  aur:
    name:
      - bspwm-git
    user: "{{ user.name }}"

- name: Verify that default applications file exists
  file: path=/etc/xdg/mimeapps.list state=touch

- name: Verify header in default applications file
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    state: present
    line: '[Default Applications]'
    insertbefore: BOF

- name: Push window switcher script
  copy: 
    src: window-switch.sh 
    dest: /usr/local/bin/window-switch
    mode: 0755
  tags:
    - fzf

- name: Push browser tab switcher script
  copy: 
    src: tab-switch.sh 
    dest: /usr/local/bin/tab-switch
    mode: 0755
  tags:
    - i3
    - fzf

- name: Create bspwm directory
  file:
    path: /home/{{ user.name }}/.config/bspwm
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags:
    - bspwm
    - bspwmrc

- name: Push bspwm config
  copy: 
    src: bspwmrc
    dest: /home/{{ user.name }}/.config/bspwm/bspwmrc
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags:
    - bspwm
    - bspwmrc

- name: Create polybar directory
  file:
    path: /home/{{ user.name }}/.config/polybar
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags:
    - polybar
    - polybarrc

- name: Push polybar config
  copy: 
    src: bspwmrc
    dest: /home/{{ user.name }}/.config/polybar/polybar
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags:
    - polybar
    - polybarrc
