---
- name: Install Xorg
  pacman: name=xorg-server state=present

- name: Install Xinit
  pacman: name=xorg-xinit state=present

- name: Install xmodmap
  pacman: name=xorg-xmodmap state=present

- name: Install xdpyinfo
  pacman: name=xorg-xdpyinfo state=present

- name: Install xev
  pacman: name=xorg-xev state=present

- name: Install xorg-sessreg
  pacman: name=xorg-sessreg state=present

- name: Install xorg-xwininfo
  pacman: name=xorg-xwininfo state=present

- name: Install xautomation
  pacman: name=xautomation state=present

- name: Install video driver(s)
  pacman:
    name: "{{ video_drivers }}"
    state: present

- name: Add user to video group
  user: name={{ user.name }} groups=video append=yes
  tags:
    - user

- name: Install Flock
  aur:
    name: haskell-filelock
    user: "{{ user.name }}"
  tags:
    - flock

- name: Install Flock
  aur:
    name: x11vnc-git
    user: "{{ user.name }}"
  tags:
    - x11vnc
    - video

- name: Push virtual desktop setup
  template:
    src: set-xrandr-virtual.sh.j2
    dest: /usr/local/bin/set-xrandr-virtual
    mode: 0755
  tags:
    - xrandr
    - video

- name: Push x11vnc script for virtual screen
  template:
    src: host-virtual-screen.sh.j2
    dest: /usr/local/bin/host-virtual-screen
    mode: 0755
  tags:
    - xrandr
    - video

- name: Prevent screen tearing
  template:
    src: 20-intel.conf.j2
    dest: /etc/X11/xorg.conf.d/20-intel.conf
  when: "'xf86-video-intel' in video_drivers"
  tags:
    - video

- name: Install floating window script
  template:
    src: float.sh.j2
    dest: /usr/local/bin/float
    mode: 0755
  tags:
    - fzf

- include: sxhkd.yml
- include: unclutter.yml
- include: autorandr.yml
- include: srandrd.yml
- include: termite.yml
- include: autocutsel.yml
- include: xdg.yml
