---
- name: Install sxhkd
  pacman:
    name: sxhkd
    state: present
  tags:
    - sxhkd

- name: Create sxhkd config dir
  file:
    path: /home/{{ user.name }}/.config/sxhkd
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags:
    - sxhkd
    - sxhkdrc

- name: Push sxhkdrc
  copy:
    src: rc/sxhkdrc
    dest: /home/{{ user.name }}/.config/sxhkd/sxhkdrc
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags:
    - sxhkd
    - sxhkdrc