---
- name: Install taskwarrior
  pacman: name=task state=present

- name: Install timewarrior
  pacman: name=timew state=present
  notify:
    - refresh holidays

- name: Install taskopen
  aur: name=taskopen user={{ user.name }}
  tags:
    - aur

- name: Install scripts
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item | basename | splitext | first }}"
    mode: 0755 
  with_fileglob:
    - files/bin/*
