---
- name: Install pandoc and dependencies
  pacman:
    name:
      - pandoc
      - pandoc-citeproc
    state: present

- name: Install xsv
  aur:
    name: xsv
    user: "{{ user.name }}"
  tags:
    - aur
