---
- name: SSH | Install
  block: 
    - name: SSH | Install | OpenSSH
      pacman: name=openssh state=present

    - name: SSH | Install | sshfs
      pacman: name=sshfs state=present

    - name: SSH | Install | autossh
      pacman: name=autossh state=present

    - name: SSH | Install | Mosh
      aur: 
        name: mosh-git
        user: "{{ user.name }}"

# - name: Push OpenSSH daemon configuration file
#   template: src=sshd_config.j2 dest=/etc/ssh/sshd_config

# - name: Copy fuse configuration file
#   copy: src=fuse.conf dest=/etc/fuse.conf

# - name: Install keychain
#   pacman: name=keychain state=present

- name: Make directory for user SSH key
  file:
    path: /home/{{ user.name }}/.ssh 
    state: directory 
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: SSH | Config
  block:
    - name: SSH | Config | Touch
      file:
        path: /home/{{ user.name }}/.ssh/config
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
        access_time: preserve
        modification_time: preserve
        state: touch

    - name: SSH | Config | Use ~/.secrets
      blockinfile:
        path: /home/{{ user.name }}/.ssh/config
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
        block: |
          host *
            IdentityFile ~/.secrets/ssh/id_rsa

