---
- include: tlp.yml

- name: Copy logind configuration file
  copy: src=logind.conf dest=/etc/systemd/logind.conf

- name: Push low battery warning script
  copy: src=lowbatt.sh dest=/usr/local/bin/lowbatt mode=0755

- name: Push low battery warning service file
  template: src=lowbatt.service.j2 dest=/etc/systemd/system/lowbatt.service
  notify:
    - reload systemd config

- name: Push low battery timer file
  template: src=lowbatt.timer.j2 dest=/etc/systemd/system/lowbatt.timer
  notify:
    - reload systemd config
    - restart lowbatt

- name: Enable and start lowbatt timer
  service: name=lowbatt.timer enabled=yes state=started

- name: Install light
  pacman: name=light state=present

- name: Install powertop
  pacman: name=powertop state=present

- name: Install powerstat
  aur: name=powerstat-git user={{ user.name }}
  tags:
    - aur

- name: Install cmake for battery-stats
  pacman: name=cmake state=present

- name: Install battery-stats
  aur:
    name: battery-stats-git
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install battop
  aur:
    name: battop
    user: "{{ user.name }}"
  tags:
    - aur
