---
- name: Install scripts
  become: true
  tags:
    - bin
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item | basename | splitext | first }}"
    mode: 0755 
  with_fileglob:
    - files/bin/*

- name: Install
  block:
    - name: Install
      aur:
        name: kitty-git

- name: Config
  tags:
    - kitty
    - kittyrc
    - rc
  block: 
    - name: Config | Directory
      file:
        path: "{{ profile.exports.XDG_CONFIG_HOME }}/kitty"
        state: directory
        owner: "{{ user.name }}"
        group: "{{ user.group }}"

    - name: Config | Push
      copy: 
        src: rc/kitty.conf
        dest: "{{ profile.exports.XDG_CONFIG_HOME }}/kitty/kitty.conf"
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
