## Options section
setopt correct                                                  # Auto correct mistakes
setopt extendedglob                                             # Extended globbing. Allows using regular expressions with *
setopt nocaseglob                                               # Case insensitive globbing
setopt rcexpandparam                                            # Array expension with parameters
setopt nocheckjobs                                              # Don't warn about running processes when exiting
setopt numericglobsort                                          # Sort filenames numerically when it makes sense
setopt nobeep                                                   # No beep
setopt appendhistory                                            # Immediately append history instead of overwriting
setopt histignorealldups                                        # If a new command is a duplicate, remove the older one
setopt autocd                                                   # if only directory path is entered, cd there.

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'       # Case insensitive tab completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"         # Colored completion (different colors for dirs/files/etc)
zstyle ':completion:*' rehash true                              # automatically find new executables in path 
# Speed up completions
zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
HISTFILE=${HOME}/.zhistory
HISTSIZE=999999999
SAVEHIST=$HISTSIZE
WORDCHARS=${WORDCHARS//\/[&.;]}                                 # Don't consider certain characters part of the word



## Keybindings section
# Vi mode
bindkey -v

# Alias section
alias vi=nvim
alias vim=nvim

# Function section 

__fzfcmd() {
  [ -n "$TMUX_PANE" ] && { [ "${FZF_TMUX:-0}" != 0 ] || [ -n "$FZF_TMUX_OPTS" ]; } &&
    echo "fzf-tmux ${FZF_TMUX_OPTS:--d${FZF_TMUX_HEIGHT:-40%}} -- " || echo "fzf"
}

# Yay install
yin () {
  yay -Slq \
  | fzf \
    --query "${@}" \
    --multi \
    --preview 'yay -Si {1}' \
    --preview-window=top \
  | xargs -ro yay -S
}

fzf-history-widget () {
  print -z $(
    ([ -n "$ZSH_NAME" ] && fc -l 1 || history) \
    | fzf +s --tac --height "50%" \
    | sed -E 's/ *[0-9]*\*? *//' \
    | sed -E 's/\\/\\\\/g'
  )
}

fzf-cd-widget() {
  the_path=${@}

  if [ $# -eq 0 ]; then
    the_path=$(pwd)
  fi

  dir=$(
    fd --type d '' "${the_path}" \
    | fzf \
    | xargs -L 1 zsh -c 'echo "${the_path}/$0"'
  )

  cd "${dir}"
}

fzf-file-widget() {
  the_path=${@}

  if [ $# -eq 0 ]; then
    the_path=$(pwd)
  fi

  fd --type f --hidden '' "${the_path}" \
  | fzf
}

fzf-file-edit-widget() {
  fzf-file-widget "${@}" | xargs $EDITOR
}

# VIM is man
man () {
  export MANPAGER="col -b"
  eval '/usr/bin/man $@ | vim -MR +"set filetype=man" -'; 
  unset MANPAGER; 
}

# VIM is less
less () {
  vim -u ~/.config/nvim/less.vimrc -
}

just-play () {
  socket=/tmp/mpv.socket 

  killall mpv

  youtube-dl "ytsearch100:${@}" \
    -j \
    --flat-playlist \
    --skip-download \
  | jq --raw-output '.id' \
  | sed 's_^_https://youtu.be/_' \
  | mpv \
      --input-ipc-server="${socket}" \
      --ytdl-raw-options=format=bestaudio \
      --shuffle \
      --playlist=- &
}

# Theming section  
autoload -U compinit colors zcalc
compinit -d
colors

## Plugins section: Enable fish style features
# Use syntax highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# FZF keybindings
# if [[ -e /usr/share/fzf/key-bindings.zsh ]]; then
#   source /usr/share/fzf/key-bindings.zsh
# fi

# FZF completion
if [[ -e /usr/share/fzf/completion.zsh ]]; then
  source /usr/share/fzf/completion.zsh
fi

# Alias section
alias h="fzf-history-widget"
alias cc="fzf-cd-widget"
alias ch="fzf-cd-widget ${HOME}"
alias ff="fzf-file-widget"
alias fe="fzf-file-edit-widget"
alias more="less"
