---
- name: Install i3
  pacman:
    name:
      - i3-gaps
    state: present

- name: Install py3status
  pacman: name=py3status state=present

- name: Verify that default applications file exists
  file: path=/etc/xdg/mimeapps.list state=touch

- name: Verify header in default applications file
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    state: present
    line: '[Default Applications]'
    insertbefore: BOF

- name: Push window switcher script
  copy: 
    src: window-switch.sh 
    dest: /usr/local/bin/window-switch
    mode: 0755
  tags:
    - i3
    - fzf

- name: Push browser tab switcher script
  copy: 
    src: tab-switch.sh 
    dest: /usr/local/bin/tab-switch
    mode: 0755
  tags:
    - i3
    - fzf

- name: Create i3 directory
  file:
    path: /home/{{ user.name }}/.config/i3
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags:
    - i3
    - i3rc

- name: Push i3 config
  template: 
    src: config.j2
    dest: /home/{{ user.name }}/.config/i3/config
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags:
    - i3
    - i3rc


- name: Push i3-tmux-term
  template: 
    src: i3-tmux-term.sh.j2
    dest: /usr/local/bin/i3-tmux-term
    mode: 0755
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags:
    - i3

- include: rofi.yml
