#!/bin/env python

config.load_autoconfig()

config.set('colors.webpage.prefers_color_scheme_dark', True)
config.set('colors.webpage.bg', 'black')
config.set('colors.webpage.darkmode.enabled', True)

config.set('colors.tabs.bar.bg', '#000000')
config.set('colors.tabs.selected.even.fg', '#cccccc')
config.set('colors.tabs.selected.odd.fg', '#cccccc')
config.set('colors.tabs.odd.bg', '#000000')
config.set('colors.tabs.odd.fg', '#888888')
config.set('colors.tabs.even.bg', '#000000')
config.set('colors.tabs.even.fg', '#888888')

config.set('fonts.default_size', '7pt')

config.set('colors.tabs.indicator.start', '#00000000')
config.set('colors.tabs.indicator.stop', '#00000000')

config.set('tabs.favicons.show', 'pinned')
config.set('statusbar.show', 'in-mode')

config.bind(' bu', 'spawn --userscript qutewarden user')
config.bind(' bp', 'spawn --userscript qutewarden pass')
config.bind(' bb', 'spawn --userscript qutewarden both')

config.set('content.headers.user_agent', "Mozilla/5.0 (Linux; Android 10; SM-A205U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36")
