--- 
- name: Install scripts
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item | basename | splitext | first }}"
    mode: 0755 
  with_fileglob:
    - files/bin/*

#- name: Copy pacman configuration file
#  copy:
#    src: pacman.conf
#    dest: /etc/pacman.conf

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes

- name: Install inetutils for hostname
  pacman:
      name: inetutils
      state: present

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

#- name: Set kernel parameters
#  lineinfile:
#    dest: /etc/default/grub
#    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
#    state: present
#    line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ kernel_parameters }}"'
#  when: kernel_parameters is defined and bootloader == 'grub'
#  notify:
#    - rebuild grub
#  tags:
#    - kernelparams

- include: shell.yml
- include: user.yml
- include: sudo.yml
- include: packages.yml
- include: journal.yml
- include: tmux.yml
- include: pam.yml
- include: archive.yml
- include: filesystems.yml

- name: Git
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - git
  block:
    - name: Git | Name
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git.name }}"

    - name: Git | Email
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ git.email }}"
