---
- name: Install baseutils
  become: true
  pacman:
    name: 
      - autoconf
      - automake
      - binutils
      - bison
      - fakeroot
      - file
      - findutils
      - flex
      - gawk
      - gcc
      - gettext
      - grep
      - groff
      - gzip
      - libtool
      - m4
      - make
      - pacman
      - texinfo
      - which
  tags:
    - packages

- name: Create user group
  group:
    name: "{{ user.group }}"
    state: present
  tags:
    - user

- name: Create user and assign to group
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: "{{ user.shell }}"
    update_password: on_create
    uid: "{{ user.uid }}"
    groups: uucp
    append: yes
  when: user_password is defined
  tags:
    - user

- name: Install sudo
  pacman: name=sudo state=present
  tags:
    - sudo

- name: Add user to wheel group
  user: name={{ user.name }} groups=wheel append=yes
  tags:
    - sudo
    - user

- name: Copy sudo configuration
  template: src=sudoers.j2 dest=/etc/sudoers mode=440 validate='visudo -cf %s'
  tags:
    - sudo

- name: Install yay
  become: true
  pacman:
    name: yay
  tags:
    - packages
