---
- name: Install baseutils
  become: true
  pacman:
    name: 
      - autoconf
      - automake
      - binutils
      - bison
      - fakeroot
      - file
      - findutils
      - flex
      - gawk
      - gcc
      - gettext
      - grep
      - groff
      - gzip
      - libtool
      - m4
      - make
      - pacman
      - texinfo
      - which
  tags:
    - packages

- name: Install yay
  become: true
  pacman:
    name: yay
  tags:
    - packages
