---
- name: pam_environment 
  tags: 
    - env
    - config
  block: 
    - file:
        path: "/home/{{ user.name }}/.pam_environment"
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
        state: touch

    - lineinfile:
        dest: "/home/{{ user.name }}/.pam_environment"
        regexp: '{{ item.key }}='
        state: present
        line: "{{ item.key }}={{ item.value }}"
      loop: "{{ env.pam | dict2items }}"