---
- name: Install ZSH
  pacman:
    name:
      - zsh
      - zsh-completions
    state: present
  tags:
    - shell

- name: zshrc
  tags:
    - shell
    - zsh
    - zshrc
    - rc
    - config
  block:
  - name: zshrc | Push 
    copy:
      src: rc/zshrc
      dest: /home/{{ user.name }}/.zshrc
      owner: "{{ user.name }}"
      group: "{{ user.group }}"

  - name: zshrc | Spaceship
    aur:
      name: spaceship-prompt-git
      user: "{{ user.name }}"

- name: Set zsh as default shell
  user: 
    name: "{{ user.name }}"
    shell: /usr/bin/zsh