---
- name: Install ZSH
  pacman:
    name:
      - zsh
      - zsh-completions
    state: present
  tags:
    - shell

- name: Push zshrc
  copy:
    src: rc/zshrc
    dest: /home/{{ user.name }}/.zshrc
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags:
    - shell
    - zsh
    - zshrc
    - rc
    - config

- name: Set zsh as default shell
  user: 
    name: "{{ user.name }}"
    shell: /usr/bin/zsh