---
- name: pam_environment
  block: 
    - file:
        path: "/home/{{ user.name }}/.pam_environment"
        state: touch
      tags: 
        - env

    - lineinfile:
        dest: "/home/{{ user.name }}/.pam_environment"
        regexp: '{{ item.key }}='
        state: present
        line: "{{ item.key }}={{ item.value }}"
      loop: "{{ env.pam | dict2items }}"
      tags: 
        - env