---
- name: Install
  become: true
  pacman:
    name: neovim
    state: present

- name: Neovim 
  tags:
    - vimrc 
    - nvimrc 
    - neovimrc 
    - rc 
  block: 
    - name: Install python-pip
      pacman:
        name: python-pip
        state: latest

    - name: Install python support
      pip:
        name: neovim
        state: latest

    - name: Install nodejs
      become: true
      pacman:
        name: nodejs
        state: present

    - name: Install ripgrep
      become: true
      pacman:
        name: ripgrep
        state: present

    - name: Install lf
      become: true
      become_user: "{{ user.name }}"
      aur:
        name: lf-bin
        state: present

    - name: Install elm
      become: true
      become_user: "{{ user.name }}"
      aur:
        name: elm-language-server

    - name: Install plugins
      become: true
      become_user: "{{ user.name }}"
      shell: nvim +PlugInstall +qall --headless
      
