secrets: 
    repo: "git@github.com:simonwjackson/secrets"
    location: /home/{{ user.name }}/.secrets

taskwarrior: |
    taskd.server=freecinc.com:53589
    taskd.key=\/home\/simonwjackson\/.secrets\/taskwarrior\/freecinc_7de71510.key.pem
    taskd.certificate=\/home\/simonwjackson\/.secrets\/taskwarrior\/freecinc_7de71510.cert.pem
    taskd.ca=\/home\/simonwjackson\/.secrets\/taskwarrior\/freecinc_7de71510.ca.pem
    taskd.credentials=FreeCinc\/freecinc_7de71510\/a5b8546f-d013-4b2c-b60f-62de3397f7c7

user:
    uid: 1000
    name: simonwjackson
    group: simonwjackson
    shell: /usr/bin/zsh
    email: hello@simonwjackson.io
    log:
        dir: log
        rotate: 8

git:
  name: "Simon W. Jackson"
  email: "simon@simonwjackson.com"

dotfiles:
    url: git@github.com:simonwjackson/dotfiles.git
    destination: projects/dotfiles
    rcup_flags: -fx README.md

aur:
    dir: aur
    packages:
        - yay
        - downgrade
        - zplug
        - miller
        - myrepos
        - ctmg
        - spiped

ssh:
    port: 22
    user_key: /root/id_rsa
    enable_sshd: True

gnupg:
    enable_agent: True
    emulate_ssh: True

mail:
    sync_tool: isync
    sync_pim: True
    sync_taskwarrior: True
    sync_notmuch: False
    sync_time: 5min
    sync_boot_delay: 2min
    sync_on: trusted

network:
    spoof_mac: True
    conn_check:
        interval: 0
    trusted_uuid:
        - b21284e6-01af-492f-8bea-45a69ef22a23
        - 4ddd6988-aad1-4927-b650-ea7d24e0138b
        - f9b3c62c-2d9f-450a-ac9b-528ba4c85ded
        - b94375d1-70f8-424f-a6d7-dc52d0ab7288
        - f74f2bd5-8748-4e1e-98f9-dae2dd44b916
        - faeec88c-79ec-4840-ab25-ea356af8a81b

editors:
    - neovim

video_drivers: 
  - xf86-video-intel 

base_packages:
    - base-devel
    - bc
    - coreutils
    - cpulimit
    - dateutils
    - dmidecode
    - fwupd
    - fzf
    - git
    - jq
    - man-db
    - man-pages
    - minicom
    - moreutils
    - pacman-contrib
    - pv
    - python-keyring
    - python-secretstorage
    - ranger
    - rsync
    - ruby
    - screen
    - termdown
    - tig
    - python-pip
    - bluez-utils
    - xterm

filesystem_packages:
    - dosfstools
    - ntfs-3g
    - exfat-utils

browser_choices:
    - firefox -P default
    - firefox -P work
    - firewarden chromium
    - firewarden -c qutebrowser
    - tor-browser-en
    - play
    - qcode
    - "| xclip -selection c"

passwordless_sudo:
    - /usr/bin/openvpn*

tarsnapper:
  deltas: 1h 1d 7d 30d 365d
  period: DAILY
  ac_only: True
  run_on: trusted
  random_delay: 600

gitannex:
    stop_on_untrusted: True

bitlbee:
    run_on: trusted
    torify: True

bootloader: grub

postgresql:
    enable: True
    root: /home/postgres

fingerprint: False

etesync: False

tor:
    run_on: trusted

localtime:
    run_on: trusted

unbound:
    tls: True
    roothints_update: trusted
    nameservers:
        - 1.1.1.1@853#cloudflare-dns.com  # Cloudflare
        - 9.9.9.9@853#dns.quad9.net  # Quad9
    private_domains:
        - corp
        - home
        - intranet
        - lan
        - mesh
        - private
    allow_lan_dns: True

bluetooth:
    disable: False

cryptshot:
    - name: alta
      uuid: 0a0db776-84c5-48e1-9079-cacfbc5de8a3
      keyfile: /home/pigmonkey/.keys/usb-alta.key
      retain:
        - level: daily
          interval: 7
        - level: weekly
          interval: 6
        - level: monthly
          interval: 3
    - name: bishorn
      uuid: baeb40a2-b19e-4adc-8ef6-44ee720a4d1a
      keyfile: /home/pigmonkey/.keys/usb-bishorn.key
      retain:
        - level: daily
          interval: 7
        - level: weekly
          interval: 6
        - level: monthly
          interval: 3
    - name: pilchuck
      uuid: d96a0fc3-7ea1-42f7-b0d0-42e573c478bd
      keyfile: /home/pigmonkey/.keys/usb-pilchuck.key
      retain:
        - level: daily
          interval: 7
        - level: weekly
          interval: 6
        - level: monthly
          interval: 3

journal:
    max_size: 500M

udisks:
    auto_mount: False
    shared_mount: True

hostsctl:
    url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

goesimage:
    run_time: 15min
    run_boot_delay: 2min
    run_on: trusted
    flags: -w -e 

desktop_environment: bspwm

base_fonts:
    - adobe-source-code-pro-fonts
    - cantarell-fonts
    - gsfonts
    - noto-fonts
    - terminus-font
    - tex-gyre-fonts
    - ttf-caladea
    - ttf-carlito
    - ttf-dejavu
    - ttf-droid
    - ttf-fira-mono
    - ttf-ibm-plex
    - ttf-inconsolata
    - ttf-liberation
    - ttf-opensans
    - ttf-ubuntu-font-family

aur_fonts:
    #- ttf-bitstream-charter
    - ttf-cooper-hewitt
    - ttf-courier-prime
    - ttf-heuristica
    - ttf-merriweather
    - ttf-merriweather-sans
    - ttf-oswald
    - ttf-quintessential
    - ttf-signika

syncthing:
    run_on: trusted
    open_ports: true

mirrorlist:
    run_on: trusted

units:
    run_on: trusted

pkgfile:
    run_on: trusted

hardened:
    enable_namespaces: true

kernel_parameters: "quiet consoleblank=60"

profile: 
  umask: '022'
  path: 
    - /usr/local/sbin
    - /usr/local/bin
    - /usr/bin/core_perl
    - /usr/bin
    - "$HOME/.bin"
  exports: 
    XDG_DATA_HOME: "/home/{{ user.name }}"
    XDG_CONFIG_HOME: "/home/{{ user.name }}/.config"
    XDG_CONFIG_DIRS: "/usr/etc/xdg:/etc/xdg"
    BROWSER: qutebrowser
    TERMINAL: kitty
    TERM: xterm-256color
    EDITOR: nvim
    VISUAL: nvim
    PAGER: less
  unset:
    # Termcap is outdated, old, and crusty, kill it.
    - TERMCAP
    # Man is much better than us at figuring this out
    - MANPATH

env:
  pam:
    TZ: "America/Chicago"
    LANG: "en_US.utf8"
    LC_CTYPE: "en_US.UTF-8"
    LC_NUMERIC: "en_US.UTF-8"
    LC_TIME: "en_US.UTF-8"
    LC_COLLATE: "C"
    LC_MONETARY: "en_US.UTF-8"
    LC_MESSAGES: "en_US.UTF-8"
    LC_PAPER: "en_US.UTF-8"
    LC_NAME: "en_US.UTF-8"
    LC_ADDRESS: "en_US.UTF-8"
    LC_TELEPHONE: "en_US.UTF-8"
    LC_MEASUREMENT: "en_US.UTF-8"
    LC_IDENTIFICATION: "en_US.UTF-8"
    LC_ALL: ""
